#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team_42_web_Service
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database1")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRecruiter(Recruiter instance);
    partial void UpdateRecruiter(Recruiter instance);
    partial void DeleteRecruiter(Recruiter instance);
    partial void InsertJobPost(JobPost instance);
    partial void UpdateJobPost(JobPost instance);
    partial void DeleteJobPost(JobPost instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Database1ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Recruiter> Recruiters
		{
			get
			{
				return this.GetTable<Recruiter>();
			}
		}
		
		public System.Data.Linq.Table<JobPost> JobPosts
		{
			get
			{
				return this.GetTable<JobPost>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Recruiter")]
	public partial class Recruiter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _R_Id;
		
		private string _R_Name;
		
		private string _R_Email;
		
		private string _R_DOB;
		
		private string _R_Password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnR_IdChanging(int value);
    partial void OnR_IdChanged();
    partial void OnR_NameChanging(string value);
    partial void OnR_NameChanged();
    partial void OnR_EmailChanging(string value);
    partial void OnR_EmailChanged();
    partial void OnR_DOBChanging(string value);
    partial void OnR_DOBChanged();
    partial void OnR_PasswordChanging(string value);
    partial void OnR_PasswordChanged();
    #endregion
		
		public Recruiter()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int R_Id
		{
			get
			{
				return this._R_Id;
			}
			set
			{
				if ((this._R_Id != value))
				{
					this.OnR_IdChanging(value);
					this.SendPropertyChanging();
					this._R_Id = value;
					this.SendPropertyChanged("R_Id");
					this.OnR_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Name", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string R_Name
		{
			get
			{
				return this._R_Name;
			}
			set
			{
				if ((this._R_Name != value))
				{
					this.OnR_NameChanging(value);
					this.SendPropertyChanging();
					this._R_Name = value;
					this.SendPropertyChanged("R_Name");
					this.OnR_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Email", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string R_Email
		{
			get
			{
				return this._R_Email;
			}
			set
			{
				if ((this._R_Email != value))
				{
					this.OnR_EmailChanging(value);
					this.SendPropertyChanging();
					this._R_Email = value;
					this.SendPropertyChanged("R_Email");
					this.OnR_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_DOB", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string R_DOB
		{
			get
			{
				return this._R_DOB;
			}
			set
			{
				if ((this._R_DOB != value))
				{
					this.OnR_DOBChanging(value);
					this.SendPropertyChanging();
					this._R_DOB = value;
					this.SendPropertyChanged("R_DOB");
					this.OnR_DOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Password", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string R_Password
		{
			get
			{
				return this._R_Password;
			}
			set
			{
				if ((this._R_Password != value))
				{
					this.OnR_PasswordChanging(value);
					this.SendPropertyChanging();
					this._R_Password = value;
					this.SendPropertyChanged("R_Password");
					this.OnR_PasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JobPost")]
	public partial class JobPost : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _P_ID;
		
		private string _P_Description;
		
		private string _P_Date;
		
		private string _R_Id;
		
		private string _Company;
		
		private string _Location;
		
		private string _Qualification;
		
		private string _Salary;
		
		private string _Experience;
		
		private string _Deadline;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnP_IDChanging(int value);
    partial void OnP_IDChanged();
    partial void OnP_DescriptionChanging(string value);
    partial void OnP_DescriptionChanged();
    partial void OnP_DateChanging(string value);
    partial void OnP_DateChanged();
    partial void OnR_IdChanging(string value);
    partial void OnR_IdChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnQualificationChanging(string value);
    partial void OnQualificationChanged();
    partial void OnSalaryChanging(string value);
    partial void OnSalaryChanged();
    partial void OnExperienceChanging(string value);
    partial void OnExperienceChanged();
    partial void OnDeadlineChanging(string value);
    partial void OnDeadlineChanged();
    #endregion
		
		public JobPost()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int P_ID
		{
			get
			{
				return this._P_ID;
			}
			set
			{
				if ((this._P_ID != value))
				{
					this.OnP_IDChanging(value);
					this.SendPropertyChanging();
					this._P_ID = value;
					this.SendPropertyChanged("P_ID");
					this.OnP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Description", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string P_Description
		{
			get
			{
				return this._P_Description;
			}
			set
			{
				if ((this._P_Description != value))
				{
					this.OnP_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._P_Description = value;
					this.SendPropertyChanged("P_Description");
					this.OnP_DescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Date", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Date
		{
			get
			{
				return this._P_Date;
			}
			set
			{
				if ((this._P_Date != value))
				{
					this.OnP_DateChanging(value);
					this.SendPropertyChanging();
					this._P_Date = value;
					this.SendPropertyChanged("P_Date");
					this.OnP_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string R_Id
		{
			get
			{
				return this._R_Id;
			}
			set
			{
				if ((this._R_Id != value))
				{
					this.OnR_IdChanging(value);
					this.SendPropertyChanging();
					this._R_Id = value;
					this.SendPropertyChanged("R_Id");
					this.OnR_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qualification", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string Qualification
		{
			get
			{
				return this._Qualification;
			}
			set
			{
				if ((this._Qualification != value))
				{
					this.OnQualificationChanging(value);
					this.SendPropertyChanging();
					this._Qualification = value;
					this.SendPropertyChanged("Qualification");
					this.OnQualificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salary", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string Salary
		{
			get
			{
				return this._Salary;
			}
			set
			{
				if ((this._Salary != value))
				{
					this.OnSalaryChanging(value);
					this.SendPropertyChanging();
					this._Salary = value;
					this.SendPropertyChanged("Salary");
					this.OnSalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Experience", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string Experience
		{
			get
			{
				return this._Experience;
			}
			set
			{
				if ((this._Experience != value))
				{
					this.OnExperienceChanging(value);
					this.SendPropertyChanging();
					this._Experience = value;
					this.SendPropertyChanged("Experience");
					this.OnExperienceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deadline", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Deadline
		{
			get
			{
				return this._Deadline;
			}
			set
			{
				if ((this._Deadline != value))
				{
					this.OnDeadlineChanging(value);
					this.SendPropertyChanging();
					this._Deadline = value;
					this.SendPropertyChanged("Deadline");
					this.OnDeadlineChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
